project:
  type: website

execute:
  freeze: auto

website:
  title: "H's notes on Data Structuress and Algorithms"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/HangenYuu/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme:
      - zephyr
      - custom.scss
    css: styles.css
    highlight-style: solarized